apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logoutput
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nafay-0/DevOps-With-Kubernetes.git
    targetRevision: main
    path: LogOutput/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
