apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nafay-0/DevOps-With-Kubernetes.git
    targetRevision: main
    path: ToDoApp/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nafay-0/DevOps-With-Kubernetes.git
    targetRevision: main
    path: ToDoApp/backend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
